### ISSUE TITLE
Fails zip extraction on windows

### ISSUE THREAD

**Issue by Puresonality** [klem23/open_orchestra#1]
Hi, thank you so much for making this tool. I don't know if it is in development anymore but I certainly hope so.

The program worked perfectly for the university of iowa samples. When I went to do the philharmonia samples, the program returned that it was a bad zip. It downloaded the correct zip file, but failed to extract it. Here is the message:

`python open_orch.py philharmonia.json
Using orchestra philharmonia.json
Extract phil_tmp/dwnld/trombone.zip
Traceback (most recent call last):
  File "open_orch.py", line 217, in <module>
    file_zip = zipfile.ZipFile(dst_file, "r")
  File "C:\Program Files\Python\lib\zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python\lib\zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file`

It is trombone instead of french horn because I temporarily removed the french horn dataset from the json file, but this same message would usually appear for french horn anyway. Thank you.

**Comment by klem23** [comment]
Hi !
Sorry for the late reply
You're using on windows, cool. I made it under linux. 

Apparently it doesn't recognize the zip file for the french horn and the trombone.
Can you try manually : download it and see if you can unzip it ?
[http://www.philharmonia.co.uk/assets/audio/samples/french%20horn/french%20horn.zip](url)
[http://www.philharmonia.co.uk/assets/audio/samples/trombone/trombone.zip](url)
Also if you remove also the french horn (and so on), it keep failing ?

Have you enough space on the drive where you download the samples (it use a lot of space) ?

Otherwise, I need to get back on it, I was still having some blank at the beginning on some sample, and it was terrible to play. And add some error management like for your case.
Also I need to to put the SFZs I generated on my website, I just see everything is white on it....
